-- para acessar o mysql no terminal
-- mysql -u root -p 
-- senha ifpe

-- para criar o banco
-- create database camila;

-- para usar o banco
-- use camila;

-- para criar as tabelas


CREATE TABLE `TB_ASSOCIACOES` (
  `ID_ASSOC` int(11) NOT NULL AUTO_INCREMENT,
  `NOME_FANTASIA` varchar(255) NOT NULL,
  `CNPJ` varchar(255) NOT NULL,
  `TELEFONE` varchar(11) DEFAULT NULL,
  `CELULAR` varchar(11) NOT NULL,
  `FACEBOOK` varchar(255) DEFAULT NULL,
  `RUA` varchar(255) NOT NULL,
  `BAIRRO` varchar(255) NOT NULL,
  `CIDADE` varchar(255) NOT NULL,
  `NOME_RESPONSAVEL` varchar(255) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `SENHA` varchar(255) NOT NULL,
  PRIMARY KEY (`ID_ASSOC`),
  UNIQUE KEY `UQ_CNPJ` (`CNPJ`),
  UNIQUE KEY `UQ_EMAIL` (`EMAIL`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

CREATE TABLE `TB_NOTICIAS` (
  `ID_NOT` int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORIA` varchar(255) NOT NULL,
  `TITULO` varchar(255) NOT NULL,
  `SUBTITULO` varchar(255) DEFAULT NULL,
  `TEXTO` text NOT NULL,
  `ARQUIVO` longblob,
  `PUBLICADO` boolean,
  `DATA` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `NOT_ASSOC_FK` int(11) NOT NULL,
  PRIMARY KEY (`ID_NOT`));

ALTER TABLE TB_NOTICIAS ADD CONSTRAINT `NOT_ASSOC_FK` FOREIGN KEY (`NOT_ASSOC_FK`) REFERENCES `TB_ASSOCIACOES` (`ID_ASSOC`);

CREATE TABLE `TB_COMENTARIO` (
  `COM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COM_NOME` varchar(255) NOT NULL,
  `COM_COMENTARIO` varchar(255) NOT NULL,
  `FK_ID_NOT` int(11) NOT NULL,
  PRIMARY KEY (`COM_ID`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE TB_COMENTARIO ADD CONSTRAINT `FK_ID_NOT` FOREIGN KEY (`FK_ID_NOT`) REFERENCES `TB_NOTICIAS` (`ID_NOT`);